ctl/booking/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    url(r'^$', views.booking, name="booking"),
    url(r'^booking2/$', views.booking2, name="booking2"),
    url(r'^booking2/(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2})/$', views.booking2, name="booking2d"),
    url(r'^booking3/(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<slot>[a-z]+)/$', views.booking3, name="booking3"),
    url(r'^booking4/(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<slot>[a-z]+)/(?P<contractor_id>[0-9]+)/$', views.booking4, name="booking4"),
    url(r'^booking5/(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2})/(?P<slot>[a-z]+)/(?P<contractor_id>[0-9]+)/$', views.booking5, name="booking5"),
]

ctl/contractor/urls.py
from django.conf.urls import url

import views

urlpatterns = [
    url(r'^my_jobs$', views.my_jobs, name="my-jobs"),
    url(r'^job_details/(?P<job_id>[0-9]+)/$', views.job_detail, name='job-detail'),
    url(r'^change_order/(?P<job_id>[0-9]+)/$', views.change_order, name='change-order'),
    url(r'^take_photo/(?P<job_id>[0-9]+)/$', views.job_photo, name='job-photo'),
    url(r'^customer_signature/(?P<job_id>[0-9]+)/$', views.customer_signature, name='customer-signature'),
    
    url(r'^authorise/$', views.authorise, name="contractor-stripe"),
    url(r'^stripe_contractor_callback/$', views.stripe_contractor_callback),
    ]

ctl/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

admin.site.site_header = 'Change The Locks Admin'

import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name="home"),
    url(r'^tandc/$', views.tandc, name="tandc"),
    url(r'^booking/', include('ctl.booking.urls')),
    url(r'^contractor/', include('ctl.contractor.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile', views.home),
    url(r'^', include('django.contrib.auth.urls')),
    
    url(r'^cancel/$', views.cancel, name="cancel"),
    
    url(r'^send_photo/$', views.send_photo, name='send-photo'),
    
    
    url(r'^fullcalendar/', TemplateView.as_view(template_name="schedule/fullcalendar.html"), name='fullcalendar'),
    url(r'^schedule/', include('schedule.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ctl/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
import datetime
import pytz

from django.core.mail import EmailMessage
from django.template.loader import render_to_string, get_template
from django.template import Context
from django.contrib.sites.shortcuts import get_current_site

import simplejson, urllib
from settings import GOOGLE_MAPS_DIRECTIONS_KEY, TIME_ZONE
from math import radians, cos, sin, asin, sqrt

from schedule.models.calendars import Calendar
from schedule.models.events import Event

class Category (models.Model):
    name = models.CharField (
        verbose_name = 'Category',
        max_length = 15,
    )
    image = models.ImageField (
        verbose_name = "Image File",
        upload_to = 'category',
        blank = True,
        null = True,
    )
    
    def __unicode__(self):
        return u'%s' % (self.name)
    
    
class Item (models.Model):
    name = models.CharField (
        verbose_name = 'Name',
        max_length = 60
    )
    description = models.TextField (
        verbose_name = 'Description',
        blank = True,
        null = True
    )
    cost = models.FloatField (
        verbose_name = "Cost",
        default = 0
    )
    time = models.IntegerField (
        verbose_name = "Installation Time (minutes)",
        default = 60
    )
    image = models.ImageField (
        verbose_name = "Image",
        upload_to = "item_images",
    )
    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
    )
    
    def __unicode__(self):
        return u'%s | %s' % (self.name, self.category)

class MyUser (models.Model):
    user = models.OneToOneField (User)
    post_code = models.CharField (
        verbose_name = "Post Code",
        max_length = 9
    )
    latitude = models.FloatField (
        verbose_name = "Latitude",
        help_text = "Google Maps calculated field based on Post Code",
        blank = True,
        null = True
    )
    longitude = models.FloatField (
        verbose_name = "Longitude",
        help_text = "Google Maps calculated field based on Post Code",
        blank = True,
        null = True
    )
    contractor = models.BooleanField(
        default = False,
        verbose_name = "Contractor"
    )
    call_out_charge = models.FloatField (
        default = 0,
        verbose_name = "Call Out Charge",
    )
    mileage = models.IntegerField (
        default = 10,
        verbose_name = "Max Travel (kilometers)",
        help_text = "Maximum distance from Post Code to Job Site"
    )
    calendar = models.OneToOneField (
        Calendar,
    )
    stripe_user_id = models.CharField (
        max_length = 255,
        verbose_name = "Stripe Token",
        help_text = "Stripe Token allowing access to contractor's stripe account",
        null=True,
        blank=True,
    )
    
    def __unicode__(self):
        return u'%s' % (self.user.username)
    
    def distance(self, pc):
        url = 'https://maps.googleapis.com/maps/api/distancematrix/json?units=imperial&origins='+self.post_code+'&destinations='+pc+'&key='+GOOGLE_MAPS_DIRECTIONS_KEY
        result = simplejson.load(urllib.urlopen(url))
        return result['rows'][0]['elements'][0]['distance']['value']
    
    def haversine(self, lat, lng):
        """
        Calculate the great circle distance between two points 
        on the earth (specified in decimal degrees)
        """
        # convert decimal degrees to radians 
        lon1, lat1, lon2, lat2 = map(radians, [self.longitude, self.latitude, lng, lat])
        # haversine formula 
        dlon = lon2 - lon1 
        dlat = lat2 - lat1 
        a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
        c = 2 * asin(sqrt(a)) 
        km = 6367 * c
        return km
    
    def checktime(self, slot, date, job_time ):
        ''' checks if contractor has availabity in timeslot and returns start time if they do '''
        if slot == 'morning':
            start_time = datetime.datetime.combine(date, datetime.time(hour=8,minute=00,tzinfo=pytz.UTC))
            end_time = datetime.datetime.combine(date, datetime.time(hour=12,minute=00,tzinfo=pytz.UTC))
        elif slot == 'afternoon' :
            start_time = datetime.datetime.combine(date, datetime.time(hour=12,minute=00,tzinfo=pytz.UTC))
            end_time = datetime.datetime.combine(date, datetime.time(hour=16,minute=00,tzinfo=pytz.UTC))
        else :
            start_time = datetime.datetime.combine(date, datetime.time(hour=16,minute=00,tzinfo=pytz.UTC))
            end_time = datetime.datetime.combine(date, datetime.time(hour=22,minute=00,tzinfo=pytz.UTC))
        events = Event.objects.filter(calendar=self.calendar, start__gte=start_time, start__lte=end_time).order_by('start')
        if len(events) < 1 : return start_time
    
        for e in events:
            time_available = e.start - start_time
            if time_available.total_seconds()/60 > job_time : return start_time
            start_time = e.end
        if (end_time - e.end).total_seconds()/60 > job_time: return start_time
        return 'None'
    
    def my_jobs (self):
        start = datetime.datetime.now().replace(hour=1, minute=00)
        return Job.objects.filter(event__calendar=self.calendar, event__start__gte=start).order_by('event__start')
    
class Customer (models.Model):
    user = models.OneToOneField (User)
    stripe_id = models.CharField (
        max_length = 255,
        verbose_name = 'Stripe Id',
        blank = True,
        null = True
    )
    
    def __unicode__(self):
        return u'%s' % (self.user.username)

class Job (models.Model):
    item = models.ManyToManyField (
        Item,
        through='Job_Item',
        verbose_name = 'Items to be installed',
    )
    customer = models.ForeignKey(
        User,
    )
    event = models.ForeignKey(
        Event,
        null = True,
    )
    housenumber = models.CharField (
        max_length = 30,
        verbose_name = "House number/name",
        blank=True
    )
    street = models.CharField (
        max_length = 30,
        verbose_name = "Street",
        blank=True
    )
    city = models.CharField (
        max_length = 30,
        verbose_name = "City",
        blank=True
    )
    post_code = models.CharField (
        max_length = 10,
        verbose_name = "Post Code",
        blank=True
    )
    signature = models.TextField (
        blank = True
    )
    additional_info = models.TextField (
        blank = True
    )
    deposit = models.FloatField(
        blank=True,
        null=True
    )
    
    def confirmation_email(self, request):
        email_body_template = 'booking/confirmation_email.txt'
        email_subject_template = 'booking/confirmation_email_subject.txt'
        context = Context()
        
        context = {}
        context['id'] = self.id
        context['item'] = self.item.name
        context['start'] = self.event.start
        context['end'] = self.event.end
        context['contractor'] = self.event.calendar.myuser.user.username
        
        context['site'] = get_current_site(request)

        subject = render_to_string(email_subject_template, context)
        # Force subject to a single line to avoid header-injection
        # issues.
        subject = ''.join(subject.splitlines())
        message = render_to_string(email_body_template,
                                   context)
        email = EmailMessage(subject,
                             message,
                             to=[self.customer.email])
        email.send()
        
    def completion_email(self, request):
        email_body_template = 'booking/completion_email.txt'
        email_subject_template = 'booking/completion_email_subject.txt'
        context = Context()
        
        context = {}
        context['id'] = self.id
        context['item'] = self.item.name
        context['start'] = self.event.start
        context['end'] = self.event.end
        context['contractor'] = self.event.calendar.myuser.user.username
        context['final_payment'] = self.balance()
        
        context['site'] = get_current_site(request)

        subject = render_to_string(email_subject_template, context)
        # Force subject to a single line to avoid header-injection
        # issues.
        subject = ''.join(subject.splitlines())
        message = render_to_string(email_body_template,
                                   context)
        email = EmailMessage(subject,
                             message,
                             to=[self.customer.email])
        email.send()
        
    def cost(self):
        j = Job_Item.objects.filter(job=self)
        x = 0
        for i in j:
            x += i.item.cost * i.count
        return x
    
    def balance(self):
        return self.cost() - self.deposit
        
    def item_count(self, item):
        try:
            j = Job_Item.objects.get(job=self, item=item)
            return j.count
        except: return 0

class Job_Item(models.Model):
    job = models.ForeignKey(Job)
    item = models.ForeignKey(Item)
    count = models.IntegerField(default = 0)
    
class JobImage (models.Model):
    job = models.ForeignKey(
        Job
    )
    image = models.ImageField(
        upload_to = 'job_image'
    )
    
    IMAGE_STAGE_OPTIONS = (
        ('pre' , 'Pre'),
        ('post' , 'Post')
    )
    stage = models.CharField(
        max_length = 4,
        choices = IMAGE_STAGE_OPTIONS,
        default = 'Pre'
    )

class Contact (models.Model):
    name = models.CharField(
        max_length = 60,
        verbose_name = 'Customer Name',
    )
    email = models.EmailField (
        verbose_name = 'Customer Email',
    )
    comments = models.TextField(
        verbose_name = 'Customer Comments'
    )
    
class ContactImage (models.Model):
    contact = models.ForeignKey(Contact)
    image = models.ImageField (

ctl/booking/forms.py
from django import forms
from django.forms import ModelForm

from localflavor.gb.forms import GBPostcodeField

class PostCodeForm(forms.Form):
    postcode = GBPostcodeField(
        label="",
        widget=forms.TextInput(attrs={'placeholder' : "Enter Your Post Code",
                                      'class' : 'form-control'}))

class AddressForm(forms.Form):
    housenumber = forms.CharField(
        max_length = 30,
        label = '',
        widget=forms.TextInput(attrs={'placeholder' : 'House Number/Name',
                                      'class' : 'form-control'})
    )
    street = forms.CharField(
        max_length = 30,
        label = '',
        widget=forms.TextInput(attrs={'placeholder' : 'Street',
                                      'class' : 'form-control',
                                      'readonly' : 'readonly'})
    )
    city = forms.CharField(
        max_length = 30,
        label = '',
        widget=forms.TextInput(attrs={'placeholder' : 'City',
                                      'class' : 'form-control',
                                      'readonly' : 'readonly'})
    )
    postcode = GBPostcodeField(
        label="",
        widget=forms.TextInput(attrs={'placeholder' : "Enter Your Post Code",
                                      'class' : 'form-control',
                                      'readonly' : 'readonly'})
    )
    additional_info = forms.CharField (
        label="",
        required = False,
        widget=forms.Textarea(attrs={'placeholder' : 'Please provide any additional information which may be useful for this job.',
                                     'class' : 'form-control'})
    )

ctl/views.py
import requests
import datetime
import simplejson, urllib
import geocoder

from django.shortcuts import render
from django.contrib import messages
from django.core.mail import EmailMessage
from django.template import Context
from django.template.loader import render_to_string, get_template

from forms import PhotoContactForm, PhotoImageForm
from ctl.booking.forms import PostCodeForm
from settings import EMAIL_HOST_USER
from models import Item, MyUser, Job, ContactImage, Review

from schedule.models.events import Event

from ctl.booking.views import booking4

def home(request):
    if 'qwerty' in request.session and 'slot' in request.session and 'date' in request.session and 'contractor_id' in request.session:
        return booking4(request, slot=request.session['slot'], date=request.session['date'], contractor_id=request.session['contractor_id'])

    variables = {}
    variables['form'] = PostCodeForm()
    variables['reviews'] = Review.objects.all()[:3]
    return render(request, 'ctl/index.html', variables)

def tandc(request):
    return render(request,'ctl/tandc.html')

def send_photo(request):
    form = PhotoContactForm()
    imageForm = PhotoImageForm()

    if request.method == 'POST':
        form = PhotoContactForm(request.POST, request.FILES)
        imageForm = PhotoImageForm(request.POST, request.FILES)
        if form.is_valid() and imageForm.is_valid():
            #here we send an email or save the record or something
            contact = form.save()
            
            
            files = request.FILES.getlist('image')
            for f in files:
                m = ContactImage (
                    image = f,
                    contact = contact
                )
                m.save()
            else : print imageForm.errors
            
            
            messages.success(request, "Message sent.  We'll be in contact as soon as we possible.")

            email_body_template = 'contact/photo_email.txt'
            email_subject_template = 'contact/photo_email_subject.txt'
            context = Context()

            context = {}
            context['name'] = contact.name
            context['email'] = contact.email
            context['comment'] = contact.comments

            subject = render_to_string(email_subject_template, context)
            # Force subject to a single line to avoid header-injection
            # issues.
            subject = ''.join(subject.splitlines())
            message = render_to_string(email_body_template,
                                       context)
            email = EmailMessage(subject,
                                 message,
                                 to=[EMAIL_HOST_USER])
            email.send()


    variables = {}
    variables['form'] = form
    variables['imageForm'] = imageForm

    return render(request, 'ctl/contact-form.html', variables)

def cancel(request):
    try: del request.session['qwerty']
    except: pass
    try: del request.session['slot']
    except: pass
    try: del request.session['date']
    except: pass
    try: del request.session['contractor_id']
    except: pass

    return home(request)

ctl/templates/contractor/change-job.html
{% extends 'base.html' %}
{% load static %}
{% load ctl %}

{% block page_title %}{{ request.META.HTTP_HOST }} - My Jobs{% endblock %}
{% block header_class %}header-transparent{% endblock %}

{% block css%}{% endblock %}

{% block content %}

<div class="main blue-keys">

    <div class="pt60 vh80">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-8 col-md-offset-2 background-secondary" style="text-align:center">
                    <h1>Change Job</h1>
                     {% if messages %}
                        {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                    <form action="{% url 'change-order' job.id %}" method='post'>
                        {% csrf_token %}
                        <table class="table table-condenced">
                            {% for item in items %}
                            <tr><td>{{ item.category.name }}: {{ item.name }}</td><td><input type="number" name="item_{{item.id}}" class="form-control" value="{{job|item_count:item}}"></td></tr>
                            {% endfor %}
                        </table>
                        <button type="submit" class="btn btn-primary btn-block">Update Order</button>
                        <a href="{% url 'job-detail' job.id %}" class="btn btn-primary">Return to Job</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div><!-- /.main -->

{% endblock %}
    


{% block scripts %}
{% endblock %}

ctl/templates/contractor/customer-signature.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}{{ request.META.HTTP_HOST }} - My Jobs{% endblock %}
{% block header_class %}header-transparent{% endblock %}

{% block css%}
<link href="{% static 'css/signature-pad.css' %}" rel="stylesheet" type="text/css" >
{% endblock %}

{% block content %}

<div class="main blue-keys">

    <div class="pt60 vh80">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-8 col-md-offset-2 background-secondary" style="text-align:center">
                    <h1>Customer Signature</h1>
                    <p>By signing below you are accepting the job has been completed and allowing us to take the balance of payment for this work.</p>
                    <p>The balance is £{{job.balance|floatformat:2}}</p>
                        <div id="signature-pad" class="m-signature-pad">
                            <form id="signature_form" action="{% url 'customer-signature' job_id %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}{{form.as_p}}
                                <div class="m-signature-pad--body">
                                    <canvas></canvas>
                                </div>
                                <div class="m-signature-pad--footer">
                                    <div class="description">Sign above</div>
                                    <button type="button" class="button btn btn-primary clear" data-action="clear">Clear</button>
                                    <button id="submit" type="submit" class="button btn btn-primary save" >Save</h>
                                </div>
                            </form>
                        </div>
                </div>
            </div>
        </div>
    </div>

</div><!-- /.main -->

{% endblock %}
    


{% block scripts %}
<script src="{% static 'js/signature_pad.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script type="text/javascript">
$('#submit').click(function(){
    signature = canvas.toDataURL('image/png');
    $('#id_signature').val(signature);
    console.log('We parsed the signature');
    $('#signature_form').submit();
});
</script>
{% endblock %}

ctl/templates/contractor/job-detail.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}{{ request.META.HTTP_HOST }} - My Jobs{% endblock %}
{% block header_class %}header-transparent{% endblock %}

{% block css%}{% endblock %}

{% block content %}

<div class="main blue-keys">

    <div class="pt60 vh80">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-8 col-md-offset-2 background-secondary" style="text-align:center">
                    <h1>Job Detail</h1>
                     {% if messages %}
                        {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                    <table class="table table-condenced">
                        <tr><td>Job Id</td><td>{{job.id}}</td></tr>
                        <tr><td>Work</td><td>{% for item in work %}{{ item.item.name }}: {{item.count}}{% if not forloop.last %},{% endif %} {% endfor %}<br><a href="{% url 'change-order' job.id %}">Change Order</a></td></tr>
                        <tr><td>Scheduled Start</td><td>{{job.event.start|date:'d/m/Y'}} {{job.event.start|time:'H:i'}}</td></tr>
                        <tr><td>Scheduled End</td><td>{{job.event.end|date:'d/m/Y'}} {{job.event.end|time:'H:i'}}</td></tr>
                        <tr><td>Address</td><td>{{job.housenumber}} {{job.street}}, {{job.city}}, {{job.post_code}}</td></tr>
                        <tr>
                            <td>PreWork Photos</td>
                            <td>
                                {% for p in preimage %}<img width="50px" src="{{p.image.url}}">{% endfor %}
                                <a href="{% url 'job-photo' job.id %}">Take Photo</a>
                            </td>
                        </tr>
                        <tr>
                            <td>PostWork Photos</td>
                            <td>
                                {% for p in postimage %}<img width="50px" src="{{p.image.url}}">{% endfor %}
                                <a href="{% url 'job-photo' job.id %}">Take Photo</a>
                            </td>
                        </tr>
                        <tr><td>Customer Signature</td><td>{% if job.signature %}<img alt="Embedded Image" src="{{job.signature}}" width="200px">{% else %}<a href="{% url 'customer-signature' job.id %}">Get Signature</a>{% endif %}</td></tr>
                    </table>                 
                </div>
            </div>
        </div>
    </div>

</div><!-- /.main -->

{% endblock %}
    


{% block scripts %}
{% endblock %}

ctl/templates/contractor/my-jobs.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}{{ request.META.HTTP_HOST }} - My Jobs{% endblock %}
{% block header_class %}header-transparent{% endblock %}

{% block css%}{% endblock %}

{% block content %}

<div class="main blue-keys">

    <div class="pt60 vh80">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-8 col-md-offset-2 background-secondary" style="text-align:center">
                    <h1>My Jobs</h1>
                    <table class="table table-condenced">
                        <tr><th>Start</th><th>End</th><th>Work</th><th>Post Code</th><td>Details</td></tr>
                        {% for j in jobs %}
                            <tr>
                                <td>{{j.event.start|date:'d/m/Y'}} {{ j.event.start|time:'H:i' }}</td>
                                <td>{{j.event.end|date:'d/m/Y'}} {{ j.event.end|time:'H:i' }}</td>
                                <td>{{j.item.name}}</td>
                                <td>{{j.post_code}}</td>
                                <td><a href="{% url 'job-detail' j.id %}">See Detail</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>

</div><!-- /.main -->

{% endblock %}
    


{% block scripts %}
{% endblock %}

ctl/templates/contractor/take-photo.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}{{ request.META.HTTP_HOST }} - My Jobs{% endblock %}
{% block header_class %}header-transparent{% endblock %}

{% block css%}{% endblock %}

{% block content %}

<div class="main blue-keys">

    <div class="pt60 vh80">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-md-8 col-md-offset-2 background-secondary" style="text-align:center">
                    <h1>Photo</h1>
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                    <form method="post" action="{% url 'job-photo' job_id %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table class="table borderless">
                        <tr><td colspan="2"><img id="id_logo"></td></tr>
                        {{form.as_table}}    
                        </table>
                        
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a href="{% url 'job-detail' job_id %}" class="btn btn-primary">Back to Job Detail</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div><!-- /.main -->

{% endblock %}
    


{% block scripts %}
<script>
    
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#id_logo')
                .attr('src', e.target.result)
                .width(150);
        };

        reader.readAsDataURL(input.files[0]);
    }
}
</script>

{% endblock %}